### PR TITLE
fix for auto fetch gpu arch value if not provided

### PR DESCRIPTION
**Pull request by sivaram1207**

### CODE REVIEW

**Comment by jkjung-avt** [comment]
I think most people don't have "deviceQuery" executable on the PATH.  Is there a more general way to determine GPU arch on the system?  In addition, what about x86 systems with 2 or more GPU's of different kinds?

**Comment by sivaram1207** [comment]
1. I assumed that, if we wanted to run Make on a particular device automatically, cuda would be installed and 'deviceQuery' may be in PATH. Maybe, I am wrong. Alternates are writing scripts like [option: 1](https://gist.github.com/f0k/63a664160d016a491b2cbea15913d549), [option: 2](https://stackoverflow.com/questions/40695455/what-utility-binary-can-i-call-to-determine-an-nvidia-gpus-compute-capability). Thought this is simple. If not this, my preference would be option: 1 over 2.
2. I didn't consider the scenario of more than one gpu, I guess if the cc are different b/w the gpus, adding multiple arch to the arg is the solution. will update the PR with that based on what's decided in the above section.

**Comment by jkjung-avt** [comment]
Using "pycuda" might be simpler than option 1 & 2.  For example, the following should work for multiple GPUs.

```
import pycuda.autoinit
import pycuda.driver as cuda

for i in range(cuda.Device.count()):
    device = cuda.Device(i)
    print(i, device.compute_capability())
```

**Comment by sivaram1207** [comment]
yeah, this should work as "pycuda" is already one of the dependencies in this repo. I was thinking from the perspective of using just the cuda libraries to get the info, updated the PR with option: 1.

**Pull request merged**
